HappyDjango/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('', include('verifications.urls')),
    path('docs/', include('doc.urls')),
    path('courses/', include('course.urls')),
    path('admin/', include('admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/course/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  @Time : 2019/2/22 21:23 
  @Auth : Youkou 
  @Site : www.youkou.site
  @File : urls.py
  @IDE  : PyCharm
  @Edit : 2019/2/22
-------------------------------------------------
"""
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='index'),    # 主页路由
    path('<int:course_id>/', views.CourseDetailView.as_view(), name='course_detail'),
]

apps/course/models.py
from django.db import models

from utils.models import ModelBase


class Teacher(ModelBase):
    name = models.CharField(max_length=150, verbose_name="讲师姓名", help_text='讲师姓名')
    positional_title = models.CharField(max_length=150, verbose_name="职称", help_text='职称')
    profile = models.TextField(verbose_name="简介", help_text='简介')
    avatar_url = models.URLField(default="", verbose_name="头像url", help_text='头像url')

    class Meta:
        db_table = "tb_teachers"  # 指明数据库表名
        verbose_name = "讲师"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.name


class CourseCategory(ModelBase):
    name = models.CharField(max_length=100, verbose_name="课程分类名", help_text='课程分类名')

    class Meta:
        db_table = "tb_course_category"  # 指明数据库表名
        verbose_name = "课程分类"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.name


class Course(ModelBase):
    title = models.CharField(max_length=150, verbose_name="课程名", help_text='课程名')
    cover_url = models.URLField(verbose_name="课程封面图URL", help_text='课程封面图URL')
    video_url = models.URLField(verbose_name="课程视频URL", help_text='课程视频URL')
    duration = models.FloatField(default=0.0, verbose_name="课程时长", help_text='课程时长')
    profile = models.TextField(null=True, blank=True, verbose_name="课程简介", help_text='课程简介')
    outline = models.TextField(null=True, blank=True, verbose_name="课程大纲", help_text='课程大纲')

    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(CourseCategory, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = "tb_course"  # 指明数据库表名
        verbose_name = "课程"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title

apps/course/views.py
import logging

from django.shortcuts import render
from django.http import Http404
from django.views import View

logger = logging.getLogger('django')


from . import models


def course_list(request):
    """

    :param request:
    :return:
    """
    courses = models.Course.objects.only('title', 'cover_url', 'teacher__positional_title').filter(is_delete=False)
    return render(request, 'course/course.html', locals())


class CourseDetailView(View):
    """
    """
    def get(self, request, course_id):
        try:
            course = models.Course.objects.only('title', 'cover_url', 'video_url', 'profile', 'outline',
                                                'teacher__name', 'teacher__avatar_url',
                                                'teacher__positional_title', 'teacher__profile').\
                select_related('teacher').get(is_delete=False, id=course_id)
            return render(request, 'course/course_detail.html', locals())
        except models.Course.DoesNotExist as e:
            logger.info("当前课程出现如下异常：\n{}".format(e))
            raise Http404("此课程不存在！")

templates/course/course.html
{% extends 'base/base.html' %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/course/course.css' %}">
{% endblock %}

{% block title %}
在线课堂
{% endblock %}

<!-- main-contain start  -->
{% block main_start %}
<main id="course-container">
        <div class="w1200">
            <ul class="course-list">
                {% for one_course in courses %}
                  <li class="course-item">
                    <a href="{% url 'course:course_detail' one_course.id %}">
                        <img class="course-img" src="{{ one_course.cover_url }}"
                            alt="{{ one_course.title }}">
                        <div class="course-content">
                            <p class="course-info">{{ one_course.title }}</p>
                            <p class="course-author">{{ one_course.teacher.name }}({{ one_course.teacher.positional_title }})</p>
                            <p class="course-price free">免费</p>
                        </div>
                    </a>
                </li>
                {% endfor %}

{#                <li class="course-item">#}
{#                    <a href="https://www.shiguangkey.com/course/2432">#}
{#                        <img class="course-img" src="../../static/images/python_advanced.jpg"#}
{#                            alt="潭州英语">#}
{#                        <div class="course-content">#}
{#                            <p class="course-info">python 全栈开发</p>#}
{#                            <p class="course-author">不动(python金牌讲师)</p>#}
{#                            <p class="course-price free">免费</p>#}
{#                        </div>#}
{#                    </a>#}
{#                </li>#}
{##}
{#                <li class="course-item">#}
{#                    <a href="https://www.shiguangkey.com/course/2432">#}
{#                        <img class="course-img" src="../../static/images/python_web.jpg"#}
{#                            alt="潭州英语">#}
{#                        <div class="course-content">#}
{#                            <p class="course-info">django 项目</p>#}
{#                            <p class="course-author">Youkou(python讲师)</p>#}
{#                            <p class="course-price free">免费</p>#}
{#                        </div>#}
{#                    </a>#}
{#                </li>#}

            </ul>
        </div>
    </main>
{% endblock %}
<!-- main-contain  end -->

templates/course/course_detail.html
{% extends 'base/base.html' %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/course/course-detail.css' %}">
{% endblock %}

{% block title %}
视频播放
{% endblock %}

<!-- main-contain start  -->
{% block main_start %}
<div class="w1200">
    <div class="course-contain">
      <div class="course-top-contain">
        <h4 class="course-title">{{ course.title }}</h4>
        <div class="course-other clearfix">
          <div class="share-list">
            <span>分享至:</span>
            <i class="PyWhich py-weibo"></i>
{#            <i class="PyWhich py-weibo2"></i>#}
          </div>
          <div class="buy-list">
            <span class="price">免费</span>
          </div>
        </div>
      </div>
      <div class="course-video" id="course-video">
        <span class="course-data" style="display: none;" data-video-url="{{ course.video_url }}"
              data-cover-url="{{ course.cover_url }}">
        </span>
      </div>
      <div class="course-bottom-contain">
        <div class="course-detail-list">
          <div class="course-item clearfix">
            <h5 class="course-title">{{ course.teacher.name }}</h5>
            <div class="teacher-box clearfix">
              <img src="{{ course.teacher.avatar_url }}" alt="{{ course.teacher.name }}"
                   title="{{ course.teacher.name }}" class="teacher-avatar">
              <div class="teacher-info">
                <p class="teacher-name">{{ course.teacher.name }}</p>
                <p class="teacher-identify">{{ course.teacher.positional_title }}</p>
              </div>
            </div>
            <div class="item-content">
              {{ course.teacher.profile }}
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">课程简介</h5>
            <div class="item-content">
              {{ course.profile }}
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">课程大纲</h5>
            <div class="item-content">
              <p>{{ course.outline }}</p>
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">帮助中心</h5>
            <div class="item-content">
              <p>1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 </p>
              <p>2. 课程暂不支持下载观看，均为在线观看视频。 </p>
              <p>3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。</p>
              <p>4. 如有问题请咨询客服: 400-1567-315 </p>
            </div>
          </div>
          <div class="course-item clearfix">
            <h5 class="course-title">关于潭州课堂</h5>
            <div class="item-content">
              湖南潭州教育网络科技有限公司拥有千余人的优秀师资团队，是一家师资丰富、教育产品类别众多的在线培训公司。公司总部座落于美丽的星城长沙，2015年9月正式入驻芯城科技园目前拥有近两万平米办公面积。
              在潭州学习的学员已突破1000万人次在线学员覆盖全球，包括中国、加拿大、日本、美国、韩国等诸多国家。
            </div>
          </div>
        </div>
        <div class="course-side">
          <h4 class="side-title">推荐课程</h4>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
<!-- main-contain  end -->

{% block script %}
  <script src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
  <script src="{% static 'js/course/course_detail.js' %}"></script>
{% endblock %}