HappyDjango/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('', include('verifications.urls')),
    path('docs/', include('doc.urls')),
    path('courses/', include('course.urls')),
    path('admin/', include('admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  @Time : 2019/2/22 21:23 
  @Auth : Youkou 
  @Site : www.youkou.site
  @File : urls.py
  @IDE  : PyCharm
  @Edit : 2019/2/22
-------------------------------------------------
"""
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),    # 主页路由
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBanner.as_view(), name='news_banner'),
    path('news/<int:news_id>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.SearchView(), name='search'),

]

apps/news/models.py
import pytz

# from django.utils import timezone
from django.db import models
from django.conf import settings

from utils.models import ModelBase


class Tag(ModelBase):
    """
    create news tag model
    linux教程
    """
    name = models.CharField(max_length=64, verbose_name="标签名", help_text="标签名")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_tag"  # 指明数据库表名
        verbose_name = "新闻标签"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.name


class News(ModelBase):
    """
    create news model
    """
    title = models.CharField(max_length=150, verbose_name="标题", help_text="标题")
    digest = models.CharField(max_length=200, verbose_name="摘要", help_text="摘要")
    content = models.TextField(verbose_name="内容", help_text="内容")
    clicks = models.IntegerField(default=0, verbose_name="点击量", help_text="点击量")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_news"  # 指明数据库表名
        verbose_name = "新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title


class Comments(ModelBase):
    """
    子评论
    """
    content = models.TextField(verbose_name="内容", help_text="内容")
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    news = models.ForeignKey('News', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='son_comments')

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_comments"  # 指明数据库表名
        verbose_name = "评论"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def to_dict_data(self):
        shanghai_tz = pytz.timezone(settings.TIME_ZONE)
        update_time_local = shanghai_tz.normalize(self.update_time)
        # update_time = shanghai_tz.localize(self.update_time)
        comment_dict = {
            "news_id": self.news.id,
            "content_id": self.id,
            "content": self.content,
            "author": self.author.username,
            # "update_time": self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            "update_time": update_time_local.strftime('%Y年%m月%d日 %H:%M'),
            "parent": self.parent.to_dict_data() if self.parent else None,
        }
        return comment_dict

    def __str__(self):
        return '<评论{}>'.format(self.id)


class HotNews(ModelBase):
    """
    """
    PRI_CHOICES = [
        (1, "第一级"),
        (2, "第二级"),
        (3, "第三级"),
    ]
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    priority = models.IntegerField(choices=PRI_CHOICES, verbose_name="优先级", help_text="优先级")

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_hotnews"  # 指明数据库表名
        verbose_name = "热门新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return '<热门新闻{}>'.format(self.id)


class Banner(ModelBase):
    """
    """
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    ]
    image_url = models.URLField(verbose_name="轮播图url", help_text="轮播图url")
    priority = models.IntegerField(choices=PRI_CHOICES, default=6, verbose_name="优先级", help_text="优先级")
    news = models.OneToOneField('News', on_delete=models.CASCADE)

    class Meta:
        ordering = ['priority', '-update_time', '-id']
        db_table = "tb_banner"  # 指明数据库表名
        verbose_name = "轮播图"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return '<轮播图{}>'.format(self.id)

apps/news/views.py
import logging
import json

from django.shortcuts import render
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseNotFound
from haystack.views import SearchView as _SearchView
from django.conf import settings

from . import models
from . import constants
from utils.res_code import Code, error_map
from utils.json_fun import to_json_data

logger = logging.getLogger('django')
# def index(request):
#     # # 1/0
#     # name = request.META.get('HTTP_NAME')
#     # age = request.META.get('HTTP_AGE')
#     # print("name = {}, age = {}".format(name, age))
#     return render(request, 'news/index.html')


class IndexView(View):
    """

    """
    def get(self, request):
        tags = models.Tag.objects.only('name').filter(is_delete=False)
        hot_news = models.HotNews.objects.select_related('news').only('news__title', 'news__image_url', 'news_id').\
            filter(is_delete=False).order_by('priority', '-news__clicks')[:constants.SHOW_HOTNEWS_COUNT]
        return render(request, 'news/index.html', locals())


# 1、创建一个类
# 2、获取前端传过来的参数
# 3、校验参数
# 4、从数据库获取news数据
# 5、分页
# 6、返回json格式的数据

class NewsListView(View):
    """
    create news list view
    route: /news/
    """
    def get(self, request):
        try:
            tag_id = int(request.GET.get('tag_id', 0))
        except Exception as e:
            logger.error("标签错误：\n{}".format(e))
            tag_id = 0

        try:
            page = int(request.GET.get('page', 1))
        except Exception as e:
            logger.error("当前页错误：\n{}".format(e))
            page = 1

        news_queryset = models.News.objects.select_related('tag', 'author').\
            only('title', 'digest', 'image_url', 'update_time', 'tag__name', 'author__username')

        news = news_queryset.filter(is_delete=False, tag_id=tag_id) or news_queryset.filter(is_delete=False)

        paginator = Paginator(news, constants.PER_PAGE_NEWS_COUNT)
        try:
            news_info = paginator.page(page)
        except EmptyPage:
            logger.info("用户访问的页数大于总页数。")
            news_info = paginator.page(paginator.num_pages)

        news_info_list = []
        for n in news_info:
            news_info_list.append({
                'id': n.id,
                'title': n.title,
                'digest': n.digest,
                'image_url': n.image_url,
                'tag_name': n.tag.name,
                'author': n.author.username,
                'update_time': n.update_time.strftime('%Y年%m月%d日 %H:%M'),
            })

        data = {
            'total_pages': paginator.num_pages,
            'news': news_info_list
        }

        return to_json_data(data=data)


class NewsBanner(View):
    """

    """
    def get(self, request):
        banners = models.Banner.objects.select_related('news').only('image_url', 'news_id', 'news__title').\
            filter(is_delete=False)[:constants.SHOW_BANNER_COUNT]

        banners_info_list = []
        for b in banners:
            banners_info_list.append({
                'image_url': b.image_url,
                'news_id': b.news.id,
                'news_title': b.news.title
            })

        data = {
            'banners': banners_info_list
        }
        return to_json_data(data=data)


class NewsDetailView(View):
    """
    create news detail view
    route: /news/<int:news_id>/
    """
    def get(self, request, news_id):
        news = models.News.objects.select_related('tag', 'author').\
            only('title', 'content', 'update_time', 'tag__name', 'author__username').\
            filter(is_delete=False, id=news_id).first()
        if news:
            comments = models.Comments.objects.select_related('author', 'parent').\
                only('content', 'author__username', 'update_time',
                     'parent__author__username', 'parent__content', 'parent__update_time').\
                filter(is_delete=False, news_id=news_id)

            comments_list = []
            for comm in comments:
                comments_list.append(comm.to_dict_data())

            comments_num = len(comments_list)

            return render(request, 'news/news_detail.html', locals())
        else:
            return HttpResponseNotFound('<h1>Page not found!</h1>')


class NewsCommentView(View):
    """
    create news comment
    route: /news/<int:news_id>/comments/
    """
    def post(self, request, news_id):
        if not request.user.is_authenticated:
            return to_json_data(errno=Code.SESSIONERR, errmsg=error_map[Code.SESSIONERR])

        if not models.News.objects.only('id').filter(is_delete=False, id=news_id).exists():
            return to_json_data(errno=Code.PARAMERR, errmsg="文章不存在")

        # 1、获取前端传过来的json数据
        json_data = request.body
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.UNKOWNERR])
        dict_data = json.loads(json_data.decode('utf8'))

        content = dict_data.get('content')
        if not content:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])

        parent_id = dict_data.get('parent_id')
        try:
            if parent_id:
                parent_id = int(parent_id)
                if not models.Comments.objects.only('id').\
                        filter(is_delete=False, id=parent_id, news_id=news_id).exists():
                    return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        except Exception as e:
            logger.info("前端传过来的parent_id异常： \n{}".format(e))
            return to_json_data(errno=Code.PARAMERR, errmsg="未知异常")

        new_content = models.Comments()
        new_content.content = content
        new_content.news_id = news_id
        new_content.author = request.user
        new_content.parent_id = parent_id if parent_id else None
        new_content.save()

        return to_json_data(data=new_content.to_dict_data())


class SearchView(_SearchView):
    # 模版文件
    template = 'news/search.html'

    # 重写响应方式，如果请求参数q为空，返回模型News的热门新闻数据，否则根据参数q搜索相关数据
    def create_response(self):
        kw = self.request.GET.get('q', '')
        if not kw:
            show_all = True
            hot_news = models.HotNews.objects.select_related('news'). \
                only('news__title', 'news__image_url', 'news__id'). \
                filter(is_delete=False).order_by('priority', '-news__clicks')

            paginator = Paginator(hot_news, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
            try:
                page = paginator.page(int(self.request.GET.get('page', 1)))
            except PageNotAnInteger:
                # 如果参数page的数据类型不是整型，则返回第一页数据
                page = paginator.page(1)
            except EmptyPage:
                # 用户访问的页数大于实际页数，则返回最后一页的数据
                page = paginator.page(paginator.num_pages)
            return render(self.request, self.template, locals())
        else:
            show_all = False
            qs = super(SearchView, self).create_response()
            return qs

templates/news/news_detail.html
{% extends 'base/base.html' %}

{% block title %}
    文章详情页
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/news/news-detail.css' %}">
{% endblock %}

<!-- main-contain start  -->
{% block main_contain %}
    <div class="news-contain">
        <h1 class="news-title">{{ news.title }}</h1>
        <div class="news-info">
            <div class="news-info-left">
                <span class="news-author">{{ news.author.username }}</span>
                <span class="news-pub-time">{{ news.update_time }}</span>
                <span class="news-type">{{ news.tag.name }}</span>
            </div>
        </div>
        <article class="news-content">
            {{ news.content|safe }}
        </article>
        <div class="comment-contain">
            <div class="comment-pub clearfix">
                <div class="new-comment">
                    文章评论(<span class="comment-count">{{ comments_num }}</span>)
                </div>

                {% if user.is_authenticated %}
                    <div class="comment-control logged-comment" news-id="{{ news.id }}">
                        <input type="text" placeholder="请填写评论">
                        <button class="comment-btn">发表评论</button>
                    </div>
                {% else %}
                    <div class="comment-control please-login-comment" news-id="{{ news.id }}">
                        <input type="text" placeholder="请登录后参加评论" readonly>
                        <button class="comment-btn">发表评论</button>
                    </div>
                {% endif %}

            </div>

            <ul class="comment-list">
                {% for one_comment in comments_list %}
                    <li class="comment-item">
                        <div class="comment-info clearfix">
                            <img src="{% static 'images/avatar.jpeg' %}" alt="avatar" class="comment-avatar">
                            <span class="comment-user">{{ one_comment.author }}</span>
                        </div>
                        <div class="comment-content">{{ one_comment.content }}</div>

                        {% if one_comment.parent %}
                            <div class="parent_comment_text">
                                <div class="parent_username">{{ one_comment.parent.author }}</div>
                                <br/>
                                <div class="parent_content_text">
                                    {{ one_comment.parent.content }}
                                </div>
                            </div>
                        {% endif %}

                        <div class="comment_time left_float">{{ one_comment.update_time }}</div>
                        <a href="javascript:;" class="reply_a_tag right_float">回复</a>
                        <form class="reply_form left_float" comment-id="{{ one_comment.content_id }}"
                              news-id="{{ one_comment.news_id }}">
                            <textarea class="reply_input"></textarea>
                            <input type="button" value="回复" class="reply_btn right_float">
                            <input type="reset" name="" value="取消" class="reply_cancel right_float">
                        </form>

                    </li>
                {% endfor %}

            </ul>
        </div>

    </div>
{% endblock %}
<!-- main-contain  end -->


{% block script %}
    <script src="{% static 'js/news/news_detail.js' %}"></script>
{% endblock %}

templates/news/search.html
{% extends 'base/base.html' %}

{% block title %}
搜索
{% endblock %}

<!-- css link start -->
{% block link %}
<link rel="stylesheet" href="{% static 'css/news/search.css' %}">
{% endblock %}
<!-- css link end -->

<!-- main-contain start  -->
{% block main_contain %}
<div class="main-contain ">
                   <!-- search-box start -->
                   <div class="search-box">
                       <form action="" style="display: inline-flex;">

                           <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">


                           <input type="submit" value="搜索" class="search-btn">
                       </form>
                       <!-- 可以用浮动 垂直对齐 以及 flex  -->
                   </div>
                   <!-- search-box end -->
                   <!-- content start -->
                   <div class="content">
                       <!-- search-list start -->
                        {% if not show_all %}
                          <div class="search-result-list">
                            <h2 class="search-result-title">
                              搜索结果 <span style="font-weight: 700;color: #ff6620;">{{ paginator.num_pages }}</span>页
                            </h2>
                            <ul class="news-list">
                              {# 导入自带高亮功能 #}
                              {% load highlight %}
                              {% for one_news in page.object_list %}
                                <li class="news-item clearfix">
                                  <a href="{% url 'news:news_detail' one_news.id %}" class="news-thumbnail" target="_blank">
                                  <img src="{{ one_news.object.image_url }}">
                                  </a>
                                  <div class="news-content">
                                    <h4 class="news-title">
                                      <a href="{% url 'news:news_detail' one_news.id %}">
                                        {% highlight one_news.title with query %}
                                      </a>
                                    </h4>
                                    <p class="news-details">{% highlight one_news.digest with query %}</p>
                                    <div class="news-other">
                                      <span class="news-type">{{ one_news.object.tag.name }}</span>
                                      <span class="news-time">{{ one_news.object.update_time }}</span>
                                      <span
                                          class="news-author">{% highlight one_news.object.author.username with query %}

                                      </span>
                                    </div>
                                  </div>
                                </li>
                              {% endfor %}


                            </ul>
                          </div>

                        {% else %}

                          <div class="news-contain">
                            <div class="hot-recommend-list">
                              <h2 class="hot-recommend-title">热门推荐</h2>
                              <ul class="news-list">

                                {% for one_hotnews in page.object_list %}

                                  <li class="news-item clearfix">
                                    <a href="{% url 'news:news_detail' one_hotnews.news.id %}" class="news-thumbnail">
                                      <img src="{{ one_hotnews.news.image_url }}">
                                    </a>
                                    <div class="news-content">
                                      <h4 class="news-title">
                                        <a href="{% url 'news:news_detail' one_hotnews.news.id %}">{{ one_hotnews.news.title }}</a>
                                      </h4>
                                      <p class="news-details">{{ one_hotnews.news.digest }}</p>
                                      <div class="news-other">
                                        <span class="news-type">{{ one_hotnews.news.tag.name }}</span>
                                        <span class="news-time">{{ one_hotnews.update_time }}</span>
                                        <span class="news-author">{{ one_hotnews.news.author.username }}</span>
                                      </div>
                                    </div>
                                  </li>

                                {% endfor %}


                              </ul>
                            </div>
                          </div>

                        {% endif %}

                       <!-- search-list end -->
                       <!-- news-contain start -->

                    {# 分页导航 #}
                     <div class="page-box" id="pages">
                       <div class="pagebar" id="pageBar">
                          <a class="a1">{{ page.paginator.count }}条</a>
                         {# 上一页的URL地址 #}
                         {% if page.has_previous %}
                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.previous_page_number }}"
                                class="prev">上一页</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.previous_page_number }}" class="prev">上一页</a>
                           {% endif %}
                         {% endif %}
                         {# 列出所有的URL地址 #}
                         {% for num in page.paginator.page_range|slice:":10" %}
                           {% if num == page.number %}
                             <span class="sel">{{ page.number }}</span>
                           {% else %}
                             {% if query %}
                               <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ num }}"
                                  target="_self">{{ num }}</a>
                             {% else %}
                               <a href="{% url 'news:search' %}?page={{ num }}" target="_self">{{ num }}</a>
                             {% endif %}
                           {% endif %}
                         {% endfor %}

                        {# 如果页数大于10，则打两点 #}
                         {% if page.paginator.num_pages > 10 %}
                           ..

                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.paginator.num_pages }}"
                                target="_self">{{ page.paginator.num_pages }}</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.paginator.num_pages }}"
                                target="_self">{{ page.paginator.num_pages }}</a>
                           {% endif %}

                         {% endif %}

                         {# 下一页的URL地址 #}
                         {% if page.has_next %}
                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.next_page_number }}"
                                class="next">下一页</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.next_page_number }}" class="next">下一页</a>
                           {% endif %}
                         {% endif %}
                       </div>
                     </div>

                     <!-- news-contain end -->
                   </div>
                   <!-- content end -->
               </div>

<!--<div class="main-contain ">-->
  <!--&lt;!&ndash; search-box start &ndash;&gt;-->
  <!--<div class="search-box">-->
    <!--<form action="" style="display: inline-flex;">-->

      <!--<input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">-->

      <!--<input type="submit" value="搜索" class="search-btn">-->
    <!--</form>-->
    <!--&lt;!&ndash; 可以用浮动 垂直对齐 以及 flex  &ndash;&gt;-->
  <!--</div>-->
  <!--&lt;!&ndash; search-box end &ndash;&gt;-->
  <!--&lt;!&ndash; content start &ndash;&gt;-->
  <!--<div class="content">-->
    <!--&lt;!&ndash; search-list start &ndash;&gt;-->


    <!--&lt;!&ndash; search-list end &ndash;&gt;-->
    <!--&lt;!&ndash; news-contain start &ndash;&gt;-->

    <!--<div class="news-contain">-->
      <!--<div class="hot-recommend-list">-->
        <!--<h2 class="hot-recommend-title">热门推荐</h2>-->
        <!--<ul class="news-list">-->

          <!--<li class="news-item clearfix">-->
            <!--<a href="#" class="news-thumbnail">-->
              <!--<img src="../../static/images/python_gui.jpg">-->
            <!--</a>-->
            <!--<div class="news-content">-->
              <!--<h4 class="news-title">-->
                <!--<a href="#">Python GUI 教程 25行代码写一个小闹钟</a>-->
              <!--</h4>-->
              <!--<p class="news-details">-->
              <!--</p>-->
              <!--<div class="news-other">-->
                <!--<span class="news-type">PythonGUI</span>-->
                <!--<span class="news-time">11/11 18:22</span>-->
                <!--<span class="news-author">python</span>-->
              <!--</div>-->
            <!--</div>-->
          <!--</li>-->

          <!--<li class="news-item clearfix">-->
            <!--<a href="#" class="news-thumbnail">-->
              <!--<img src="../../static/images/python_advanced.jpg">-->
            <!--</a>-->
            <!--<div class="news-content">-->
              <!--<h4 class="news-title">-->
                <!--<a href="#">python高性能编程方法一</a>-->
              <!--</h4>-->
              <!--<p class="news-details">-->
              <!--</p>-->
              <!--<div class="news-other">-->
                <!--<span class="news-type">Python高级</span>-->
                <!--<span class="news-time">11/11 17:13</span>-->
                <!--<span class="news-author">python</span>-->
              <!--</div>-->
            <!--</div>-->
          <!--</li>-->

          <!--<li class="news-item clearfix">-->
            <!--<a href="#" class="news-thumbnail">-->
              <!--<img src="../../static/images/jichujiaochen.jpeg">-->
            <!--</a>-->
            <!--<div class="news-content">-->
              <!--<h4 class="news-title">-->
                <!--<a href="#">python基础 split 和 join函数比较</a>-->
              <!--</h4>-->
              <!--<p class="news-details">-->
              <!--</p>-->
              <!--<div class="news-other">-->
                <!--<span class="news-type">Python基础</span>-->
                <!--<span class="news-time">11/11 16:09</span>-->
                <!--<span class="news-author">python</span>-->
              <!--</div>-->
            <!--</div>-->
          <!--</li>-->

          <!--<li class="news-item clearfix">-->
            <!--<a href="#" class="news-thumbnail">-->
              <!--<img src="../../static/images/python_web.jpg">-->
            <!--</a>-->
            <!--<div class="news-content">-->
              <!--<h4 class="news-title">-->
                <!--<a href="#">Django调试工具django-debug-toolbar安装使用教程</a>-->
              <!--</h4>-->
              <!--<p class="news-details">-->
              <!--</p>-->
              <!--<div class="news-other">-->
                <!--<span class="news-type">python框架</span>-->
                <!--<span class="news-time">11/11 15:28</span>-->
                <!--<span class="news-author">python</span>-->
              <!--</div>-->
            <!--</div>-->
          <!--</li>-->

        <!--</ul>-->
      <!--</div>-->
    <!--</div>-->


    <!--&lt;!&ndash; news-contain end &ndash;&gt;-->
  <!--</div>-->
  <!--&lt;!&ndash; content end &ndash;&gt;-->
<!--</div>-->
{% endblock %}
<!-- main-contain  end -->

{% block hot_recommend %}
{% endblock %}

{% block script %}
{% endblock %}