HappyDjango/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('', include('verifications.urls')),
    path('docs/', include('doc.urls')),
    path('courses/', include('course.urls')),
    path('admin/', include('admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/doc/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  @Time : 2019/2/22 21:23 
  @Auth : Youkou 
  @Site : www.youkou.site
  @File : urls.py
  @IDE  : PyCharm
  @Edit : 2019/2/22
-------------------------------------------------
"""
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path('', views.doc_index, name='index'),    # 主页路由
    path('<int:doc_id>/', views.DocDownload.as_view(), name='doc_download'),

]

apps/doc/models.py
from django.db import models

from utils.models import ModelBase


class Doc(ModelBase):
    """create doc view
    """
    file_url = models.URLField(verbose_name="文件url", help_text="文件url")
    title = models.CharField(max_length=150, verbose_name="文档标题", help_text="文档标题")
    desc = models.TextField(verbose_name="文档描述", help_text="文档描述")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = "tb_docs"   # 指明数据库表名
        verbose_name = "用户"    # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title

apps/doc/views.py
import requests

from django.shortcuts import render
from django.views import View
from django.http import Http404, FileResponse
from django.utils.encoding import escape_uri_path
from django.conf import settings

from .models import Doc


def doc_index(request):
    """
    create doc index veiw
    :param request:
    :return:
    """
    docs = Doc.objects.defer("author", "create_time", "update_time", "is_delete").filter(is_delete=False)
    return render(request, 'doc/docDownload.html', locals())


class DocDownload(View):
    """
    create doc download
    route: /docs/<int:doc_id>/
    """
    def get(self, request, doc_id):
        doc = Doc.objects.only('file_url', 'title').filter(is_delete=False, id=doc_id).first()
        if doc:
            doc_url = doc.file_url
            doc_url = settings.SITE_DOMAIN_PORT + doc_url
            doc_name = doc.title
            # /home/Conner/HappyDjango/media/django项目班_英语单词2.doc
            # media/django项目班_英语单词2.doc
            res = FileResponse(open(doc.file_url[1:], 'rb'))
            # res = FileResponse(requests.get(doc_url, stream=True))

            ex_name = doc_url.split('.')[-1]
            if not ex_name:
                raise Http404("<h1>文档url异常</h1>")
            else:
                ex_name = ex_name.lower()

            if ex_name == "pdf":
                res["Content-type"] = "application/pdf"
            elif ex_name == "zip":
                res["Content-type"] = "application/zip"
            elif ex_name == "doc":
                res["Content-type"] = "application/msword"
            elif ex_name == "xls":
                res["Content-type"] = "application/vnd.ms-excel"
            elif ex_name == "docx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            elif ex_name == "ppt":
                res["Content-type"] = "application/vnd.ms-powerpoint"
            elif ex_name == "pptx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
            else:
                raise Http404("<h1>文档格式不正确</h1>")

            final_filename = doc_name + '.' + ex_name
            # doc_filename = escape_uri_path(doc_url.split('/')[-1])
            doc_filename = escape_uri_path(final_filename)
            # 设置为inline，会直接打开
            res["Content-Disposition"] = "attachment; filename*=UTF-8''{}".format(doc_filename)
            return res

        else:
            raise Http404("<h1>文档不存在！</h1>")

templates/doc/docDownload.html
{% extends 'base/base.html' %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/doc/docDownload.css' %}">
{% endblock %}

{% block title %}
  文档下载
{% endblock %}

<!-- main-contain start  -->
{% block main_contain %}
  <div class="main-contain ">
    <div class="banner">
      <img src="/media/doc_banner_2.jpg"
           alt="">
    </div>
    <div class="pay-doc-contain">
      <ul class="pay-list">
        {% for doc in docs %}
          <li class="pay-item">
          <img src="{{ doc.image_url }}" class="pay-img doc"/>
          <div class="d-contain">
            <p class="doc-title">{{ doc.title }}</p>
            <p class="doc-desc">{{ doc.desc }}</p>

            <a href="{% url 'doc:doc_download' doc.id %}" class="pay-price">下载</a>
          </div>
        </li>
        {% endfor %}


{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="d-contain">#}
{#            <p class="doc-title">python cookbook 3.0 教程</p>#}
{#            <p class="doc-desc">强烈推荐的python 教程。</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}
{##}
{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="pay-contain">#}
{#            <p class="pay-title">流畅的Python</p>#}
{#            <p class="pay-desc">【本书特色】#}
{##}
{#              本书由奋战在Python开发一线近20年的Luciano Ramalho执笔，Victor Stinner、Alex#}
{#              Martelli等Python大咖担纲技术审稿人，从语言设计层面剖析编程细节，兼顾Python 3和Python#}
{#              2，告诉你Python中不亲自动手实践就无法理解的语言陷阱成因和解决之道，教你写出风格地道的Python代码。</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}
{##}
{#        <li class="pay-item">#}
{#          <div class="pay-img doc"></div>#}
{#          <div class="pay-contain">#}
{#            <p class="pay-title">深入Flask</p>#}
{#            <p class="pay-desc">深入Flask，强烈推荐！</p>#}
{##}
{#            <!-- /www/?xxx -->#}
{#            <a href="#" class="pay-price">下载</a>#}
{#          </div>#}
{#        </li>#}

      </ul>
    </div>
  </div>
{% endblock %}
<!-- main-contain  end -->

{% block hot_recommend %}
{% endblock %}

{% block script %}
{% endblock %}